version: '3.8'

networks:
    inception_network:
        driver: bridge
        name: inception_network

volumes:
    wordpress_volume:
    #     name: wordpress_volume
    #     driver: local
    #     driver_opts:
    #       type: none
    #       device: /Users/abizyane/goinfre/data/wordpress_volume
    #       o: bind
    database_volume:
    #     name: database_volume
    #     driver: local
    #     driver_opts:
    #       type: none
    #       device: /Users/abizyane/goinfre/data/database_volume
    #       o: bind

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        expose:
          - 3306
        volumes:
          - database_volume:/var/lib/mysql/
        networks:
          - inception_network
        env_file:
          - .env
        restart: unless-stopped

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        expose:
          - 9000
        volumes:
          - wordpress_volume:/var/www/
        depends_on:
          - mariadb
        networks:
          - inception_network
        env_file:
          - .env
        restart: unless-stopped

    nginx:
        build: ./requirements/nginx
        container_name: nginx
        ports:
          - "443:443"
        volumes:
          - wordpress_volume:/var/www/
        depends_on:
          - wordpress
        networks:
          - inception_network
        restart: unless-stopped

    adminer:
        build: ./requirements/bonus/adminer
        container_name: adminer
        expose:
          - 8080
        networks:
          - inception_network
        depends_on:
          - mariadb
        restart: unless-stopped

    redis:
        build: ./requirements/bonus/redis
        container_name: redis
        expose:
          - 6379
        networks:
          - inception_network
        depends_on:
          - wordpress
        restart: unless-stopped

    website:
        build: ./requirements/bonus/website
        container_name: website
        expose:
          - 80
        networks:
          - inception_network
        depends_on:
          - wordpress
        restart: unless-stopped

    ftp:
        build: ./requirements/bonus/ftp
        container_name: ftp
        env_file:
          - .env
        ports:
          - "21:21"
          - "21000-21010:21000-21010"
        networks:
          - inception_network
        volumes:
          - wordpress_volume:/var/www
        restart: unless-stopped

    portainer:
        build: ./requirements/bonus/portainer
        container_name: portainer
        env_file:
          - .env
        expose:
          - 9000
        networks:
          - inception_network
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
