version: '3.7'
name: inception
networks:
    inception_network:
        driver: bridge
        name: inception_network

volumes:
    wordpress_volume:
        name: wordpress_volume
        driver: local
        # driver_opts:
        #   type: none
        #   device: /home/abizyane/data/wordpress_volume
        #   o: bind    
    database_volume:
        name: database_volume
        driver: local
        # driver_opts:
        #   type: none
        #   device: /home/abizyane/data/database_volume
        #   o: bind
    redis_volume:
        name: redis_volume
        driver: local

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        expose:
          - 3306
        volumes:
          - database_volume:/var/lib/mysql/
        networks:
          - inception_network
        env_file:
          - .env
        restart: always
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        expose:
          - 9000
        volumes:
          - wordpress_volume:/var/www/
        depends_on:
          - mariadb
        networks:
          - inception_network
        env_file:
          - .env
        restart: always
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        ports:
          - "443:443"
        volumes:
          - wordpress_volume:/var/www/
        depends_on:
          - wordpress
        networks:
          - inception_network
        restart: always
    adminer:
        build: ./requirements/bonus/adminer
        container_name: adminer
        ports:
          - "8080:8080"
        networks:
          - inception_network
        depends_on:
          - mariadb
        restart: always
    redis:
        build: ./requirements/bonus/redis
        container_name: redis
        expose:
          - 6379
        networks:
          - inception_network
        volumes:
          - redis_volume:/data
        restart: always
    # ftpserver:
    #     build: ./requirements/bonus/ftpserver
    #     container_name: ftpserver
    #     ports:
    #       - "21:21"
    #       - "21000-21010:21000-21010"
    #     networks:
    #       - inception_network
    #     depends_on:
    #       - wordpress
    #     volumes:
    #       - wordpress_volume:/var/www/
    #     restart: always
  